In [4]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, TargetEncoder

# **Encoding Strategies for Categorical Variables**:

- Label Encoding
- Ordinal Encoding
- One-hot Encoding
- Target Encoding
- Frequency Encoding
- Binary Encoding
- Embedding Encoding

## **Label Encoding**:

This encoding strategy assigns an integer to every unique category in the categorical variable.
> Note: Mostly used for encoding the target variable in the classification task.

## **Ordinal Encoding**:

This encoding strategy used for encoding ranked qualitative data and when there is a meaninful ranking between categories in a variable.

example: bachelor, master, PHD

## **One-hot Encoding**:

This method can encode categorical variables without introducing any order between them.
> Note: Resulting in high dimensional feature space is the problem of this encoding strategy (Curse of dimensionality).

In [5]:
diamonds = sns.load_dataset("diamonds")
print(f"Shape of the dataset: {diamonds.shape}")
diamonds.head(10)

Shape of the dataset: (53940, 10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [6]:
print("Data types in the dataset:")
diamonds.dtypes

Data types in the dataset:

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [7]:
diamonds['cut'].unique()

['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Categories (5, str): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']

In [8]:
import pandas as pd
import numpy as np

enc = OneHotEncoder(sparse_output=False)
cut_encoded = enc.fit_transform(diamonds['cut'].to_numpy().reshape(-1, 1))
cut_encoded = pd.DataFrame(
    data=cut_encoded,
    columns=enc.get_feature_names_out(input_features=["cut"]),
    dtype=np.int8
)

cols = diamonds.columns.to_list()
cols.pop(1)
diamonds = pd.concat([diamonds[cols], cut_encoded], axis=1)

In [9]:
diamonds

,carat,color,clarity,depth,table,price,x,y,z,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good
0,0.23,E,SI2,61.5,55.0,326,3.95,3.98,2.43,0,0,1,0,0
1,0.21,E,SI1,59.8,61.0,326,3.89,3.84,2.31,0,0,0,1,0
2,0.23,E,VS1,56.9,65.0,327,4.05,4.07,2.31,0,1,0,0,0
3,0.29,I,VS2,62.4,58.0,334,4.20,4.23,2.63,0,0,0,1,0
4,0.31,J,SI2,63.3,58.0,335,4.34,4.35,2.75,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,0,0,1,0,0
53936,0.72,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,0,1,0,0,0
53937,0.70,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,0,0,0,0,1
53938,0.86,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,0,0,0,1,0
53939,0.75,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,0,0,1,0,0

In [108]:
import pandas as pd

np.random.seed(42)
df = pd.DataFrame({
    'City': np.random.choice(['New York', 'London', 'Paris', 'Tokyo'], 1000),
    'Sales': np.random.normal(loc=100, scale=20, size=1000)
})

X = df['City'].to_numpy().reshape(-1, 1)
y = df['Sales'].to_numpy().reshape(-1, 1)

# encoding
one_hot_enc = OneHotEncoder(sparse_output=False)
city_onehot_encoded = one_hot_enc.fit_transform(X)
df[["City_London", "City_New York", "City_Paris", "City_Tokyo"]] = city_onehot_encoded
df

         City       Sales  City_London  City_New York  City_Paris  City_Tokyo
0       Paris  106.835120          0.0            0.0         1.0         0.0
1       Tokyo  137.523417          0.0            0.0         0.0         1.0
2    New York  119.008477          0.0            1.0         0.0         0.0
3       Paris   88.461927          0.0            0.0         1.0         0.0
4       Paris   82.031707          0.0            0.0         1.0         0.0
..        ...         ...          ...            ...         ...         ...
995  New York   90.241772          0.0            1.0         0.0         0.0
996  New York  143.146164          0.0            1.0         0.0         0.0
997     Tokyo   87.885702          0.0            0.0         0.0         1.0
998     Tokyo  114.841907          0.0            0.0         0.0         1.0
999     Paris  105.985852          0.0            0.0         1.0         0.0

[1000 rows x 6 columns]

## **Target Encoding**:

This encoding method uses the target variable to show how each category influences the target variable
> Note: Useful for categorical variables with high cardinality cause doesn't make more than one feature. It prevents the curse of dimensionality.

In [111]:
X = df['City'].to_numpy().reshape(-1, 1)
y = df['Sales'].to_numpy().reshape(-1, 1)

target_encoder = TargetEncoder()
city_target_encoded = target_encoder.fit_transform(X, y)
df["City_target_encoded"] = city_target_encoded
df

/home/erfan_taherirani/miniconda3/envs/data-processing/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,City,Sales,City_London,City_New York,City_Paris,City_Tokyo,City_target_encoded
0,Paris,106.835120,0.0,0.0,1.0,0.0,102.286313
1,Tokyo,137.523417,0.0,0.0,0.0,1.0,100.728726
2,New York,119.008477,0.0,1.0,0.0,0.0,100.731182
3,Paris,88.461927,0.0,0.0,1.0,0.0,99.542379
4,Paris,82.031707,0.0,0.0,1.0,0.0,102.286313
...,...,...,...,...,...,...,...
995,New York,90.241772,0.0,1.0,0.0,0.0,100.952700
996,New York,143.146164,0.0,1.0,0.0,0.0,98.605123
997,Tokyo,87.885702,0.0,0.0,0.0,1.0,100.777601
998,Tokyo,114.841907,0.0,0.0,0.0,1.0,99.961949
999,Paris,105.985852,0.0,0.0,1.0,0.0,102.286313

## **Frequency Encoding**:

This method use the frequency of categories in cout or percent mode.
> Note: This encoding method is also useful for categorical variables with high cardinality.

In [128]:
def frequency_encoding(s: pd.Series) -> pd.Series:
    mapping = s.value_counts() / len(s)
    return s.map(mapping)

In [130]:
df['City_frequency'] = frequency_encoding(df['City'])
df

,City,Sales,City_London,City_New York,City_Paris,City_Tokyo,City_target_encoded,City_frequency
0,Paris,106.835120,0.0,0.0,1.0,0.0,102.286313,0.232
1,Tokyo,137.523417,0.0,0.0,0.0,1.0,100.728726,0.280
2,New York,119.008477,0.0,1.0,0.0,0.0,100.731182,0.258
3,Paris,88.461927,0.0,0.0,1.0,0.0,99.542379,0.232
4,Paris,82.031707,0.0,0.0,1.0,0.0,102.286313,0.232
...,...,...,...,...,...,...,...,...
995,New York,90.241772,0.0,1.0,0.0,0.0,100.952700,0.258
996,New York,143.146164,0.0,1.0,0.0,0.0,98.605123,0.258
997,Tokyo,87.885702,0.0,0.0,0.0,1.0,100.777601,0.280
998,Tokyo,114.841907,0.0,0.0,0.0,1.0,99.961949,0.280
999,Paris,105.985852,0.0,0.0,1.0,0.0,102.286313,0.232

## **Binary Encoding**:

This encoding method uses binary representation of the categories and can represent the categorical variable and input it to the computer but in may introduce some order between categories and introduces bias to the model.